In [73]:
import pandas as pd
import numpy as np

In [74]:
df = pd.read_csv("train.csv")

C:\Users\RISHAB\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (16,17,18,19,20,22,23,24,25,26,27,28,45,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [75]:
df

,appno,application,country.alpha2,country.name,decisiondate,docname,doctypebranch,ecli,introductiondate,issue.0,...,ccl_article=6,ccl_article=7,ccl_article=8,ccl_article=9,ccl_article=p1,ccl_article=p12,ccl_article=p4,ccl_article=p6,ccl_article=p7,importance
0,2052/08,MS WORD,ru,Russian Federation,NaN,CASE OF KOKOSHKINA v. RUSSIA,CHAMBER,ECLI:CE:ECHR:2009:0528JUD000205208,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
1,4728/07,MS WORD,tr,Turkey,NaN,CASE OF ÖZCAN v. TURKEY,COMMITTEE,ECLI:CE:ECHR:2018:0710JUD000472807,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
2,44135/06,MS WORD,si,Slovenia,NaN,CASE OF DANIJEL PEČNIK v. SLOVENIA,CHAMBER,ECLI:CE:ECHR:2012:1018JUD004413506,NaN,NaN,...,1,0,0,0,0,0,0,0,0,4
3,2607/08,MS WORD,ch,Switzerland,NaN,CASE OF PALANCI v. SWITZERLAND,CHAMBER,ECLI:CE:ECHR:2014:0325JUD000260708,NaN,NaN,...,0,0,-1,0,0,0,0,0,0,4
4,27001/06,MS WORD,ru,Russian Federation,NaN,CASE OF AMANAT ILYASOVA AND OTHERS v. RUSSIA,CHAMBER,ECLI:CE:ECHR:2009:1001JUD002700106,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8873,60085/12,MS WORD,ua,Ukraine,NaN,CASE OF RASHITOV AND OTHERS v. UKRAINE,COMMITTEE,ECLI:CE:ECHR:2018:0329JUD006008512,NaN,NaN,...,1,0,0,0,0,0,0,0,0,4
8874,19857/09,MS WORD,ru,Russian Federation,NaN,CASE OF URMANOV v. RUSSIA,COMMITTEE,ECLI:CE:ECHR:2016:1011JUD001985709,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
8875,67253/01,MS WORD,ru,Russian Federation,NaN,CASE OF BABUSHKIN v. RUSSIA,CHAMBER,ECLI:CE:ECHR:2007:1018JUD006725301,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
8876,26737/95,MS WORD,es,Spain,NaN,CASE OF BRUALLA GÓMEZ DE LA TORRE v. SPAIN,CHAMBER,ECLI:CE:ECHR:1997:1219JUD002673795,NaN,"Leases of Urban Property Act, section 135, as ...",...,-1,0,0,0,0,0,0,0,0,3
8877,21695/05,MS WORD,pl,Poland,NaN,CASE OF TUR v. POLAND,CHAMBER,ECLI:CE:ECHR:2007:1023JUD002169505,NaN,NaN,...,1,0,0,0,0,0,0,0,0,4

In [76]:
df.columns

Index(['appno', 'application', 'country.alpha2', 'country.name',
       'decisiondate', 'docname', 'doctypebranch', 'ecli', 'introductiondate',
       'issue.0',
       ...
       'ccl_article=6', 'ccl_article=7', 'ccl_article=8', 'ccl_article=9',
       'ccl_article=p1', 'ccl_article=p12', 'ccl_article=p4', 'ccl_article=p6',
       'ccl_article=p7', 'importance'],
      dtype='object', length=328)

In [77]:
df.describe()

,originatingbody,rank,respondentOrderEng,sharepointid,typedescription,article=3,article=6,article=P1,article=5,article=8,...,ccl_article=6,ccl_article=7,ccl_article=8,ccl_article=9,ccl_article=p1,ccl_article=p12,ccl_article=p4,ccl_article=p6,ccl_article=p7,importance
count,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,...,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000
mean,12.255688,1357.402719,32.342532,400864.536269,14.941879,0.180221,0.550800,0.177292,0.172787,0.116242,...,0.390178,-0.001802,0.043253,0.002591,0.064654,0.000113,0.001577,0.000225,0.000788,3.461703
std,9.504175,1446.218266,14.062796,57670.790798,0.279205,0.384393,0.497441,0.381937,0.378084,0.320533,...,0.599878,0.077974,0.320771,0.078671,0.282190,0.010613,0.058112,0.015008,0.048632,0.870096
min,4.000000,171.353943,1.000000,316255.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,1.000000
25%,5.000000,582.323181,20.000000,347609.500000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
50%,7.000000,788.466248,38.000000,394983.500000,15.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
75%,23.000000,1547.329742,45.000000,454025.250000,15.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
max,29.000000,9968.310547,49.000000,501627.000000,19.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000

In [78]:
df = df.drop(['application','country.alpha2','docname','introductiondate'],axis=1)

In [79]:
df.head()

,appno,country.name,decisiondate,doctypebranch,ecli,issue.0,issue.1,issue.10,issue.11,issue.12,...,ccl_article=6,ccl_article=7,ccl_article=8,ccl_article=9,ccl_article=p1,ccl_article=p12,ccl_article=p4,ccl_article=p6,ccl_article=p7,importance
0,2052/08,Russian Federation,NaN,CHAMBER,ECLI:CE:ECHR:2009:0528JUD000205208,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
1,4728/07,Turkey,NaN,COMMITTEE,ECLI:CE:ECHR:2018:0710JUD000472807,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
2,44135/06,Slovenia,NaN,CHAMBER,ECLI:CE:ECHR:2012:1018JUD004413506,NaN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,0,0,4
3,2607/08,Switzerland,NaN,CHAMBER,ECLI:CE:ECHR:2014:0325JUD000260708,NaN,NaN,NaN,NaN,NaN,...,0,0,-1,0,0,0,0,0,0,4
4,27001/06,Russian Federation,NaN,CHAMBER,ECLI:CE:ECHR:2009:1001JUD002700106,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4

In [80]:
df = df.drop(['decisiondate','ecli','issue.0','issue.1','issue.2','issue.3','issue.4','issue.5' \
             
             ,'issue.6','issue.7','issue.8','issue.9','issue.10','issue.11','issue.12','issue.13' \
             
             ,'issue.14','issue.15','issue.16','issue.17','issue.18','issue.19','issue.20','issue.21','issue.22'\
             
             ,'issue.23','issue.24','issue.25','issue.26'],axis=1)

In [81]:
df.head()

,appno,country.name,doctypebranch,itemid,judgementdate,kpdate,languageisocode,originatingbody,originatingbody_name,originatingbody_type,...,ccl_article=6,ccl_article=7,ccl_article=8,ccl_article=9,ccl_article=p1,ccl_article=p12,ccl_article=p4,ccl_article=p6,ccl_article=p7,importance
0,2052/08,Russian Federation,CHAMBER,001-92699,28/05/2009,28/05/2009,ENG,4,First Section,Court,...,0,0,0,0,0,0,0,0,0,4
1,4728/07,Turkey,COMMITTEE,001-184490,10/07/2018,10/07/2018,ENG,26,Second Section Committee,Court,...,0,0,0,0,0,0,0,0,0,4
2,44135/06,Slovenia,CHAMBER,001-113810,18/10/2012,18/10/2012,ENG,23,Fith Section,Court,...,1,0,0,0,0,0,0,0,0,4
3,2607/08,Switzerland,CHAMBER,001-141929,25/03/2014,25/03/2014,ENG,5,Second Section,Court,...,0,0,-1,0,0,0,0,0,0,4
4,27001/06,Russian Federation,CHAMBER,001-94585,01/10/2009,01/10/2009,ENG,4,First Section,Court,...,0,0,0,0,0,0,0,0,0,4

In [82]:
df = df.drop(['itemid','languageisocode','kpdate','judgementdate'],axis=1)

In [83]:
df.head()

,appno,country.name,doctypebranch,originatingbody,originatingbody_name,originatingbody_type,parties.0,parties.1,parties.2,rank,...,ccl_article=6,ccl_article=7,ccl_article=8,ccl_article=9,ccl_article=p1,ccl_article=p12,ccl_article=p4,ccl_article=p6,ccl_article=p7,importance
0,2052/08,Russian Federation,CHAMBER,4,First Section,Court,KOKOSHKINA,RUSSIA,NaN,685.417419,...,0,0,0,0,0,0,0,0,0,4
1,4728/07,Turkey,COMMITTEE,26,Second Section Committee,Court,ÖZCAN,TURKEY,NaN,2641.901855,...,0,0,0,0,0,0,0,0,0,4
2,44135/06,Slovenia,CHAMBER,23,Fith Section,Court,DANIJEL PEČNIK,SLOVENIA,NaN,942.213440,...,1,0,0,0,0,0,0,0,0,4
3,2607/08,Switzerland,CHAMBER,5,Second Section,Court,PALANCI,SWITZERLAND,NaN,1121.770142,...,0,0,-1,0,0,0,0,0,0,4
4,27001/06,Russian Federation,CHAMBER,4,First Section,Court,AMANAT ILYASOVA AND OTHERS,RUSSIA,NaN,704.821594,...,0,0,0,0,0,0,0,0,0,4

In [84]:
l = [X for X in df.columns]
l

['appno',
 'country.name',
 'doctypebranch',
 'originatingbody',
 'originatingbody_name',
 'originatingbody_type',
 'parties.0',
 'parties.1',
 'parties.2',
 'rank',
 'respondent.0',
 'respondent.1',
 'respondent.2',
 'respondent.3',
 'respondent.4',
 'respondentOrderEng',
 'separateopinion',
 'sharepointid',
 'typedescription',
 'article=3',
 'article=6',
 'article=P1',
 'article=5',
 'article=8',
 'article=13',
 'article=10',
 'article=2',
 'article=34',
 'article=41',
 'article=38',
 'article=35',
 'article=4',
 'article=29',
 'article=14',
 'article=P12',
 'article=9',
 'article=1',
 'article=11',
 'article=46',
 'article=P4',
 'article=17',
 'article=18',
 'article=7',
 'article=',
 'article=37',
 'article=P7',
 'article=57',
 'article=26',
 'article=27',
 'article=36',
 'article=30',
 'article=12',
 'article=56',
 'article=39',
 'article=15',
 'article=25',
 'article=P6',
 'article=19',
 'article=32',
 'article=33',
 'article=53',
 'article=28',
 'article=43',
 'article=52',
 'article=P13',
 'article=16',
 'documentcollectionid=CASELAW',
 'documentcollectionid=JUDGMENTS',
 'documentcollectionid=CHAMBER',
 'documentcollectionid=ENG',
 'documentcollectionid=COMMITTEE',
 'documentcollectionid=GRANDCHAMBER',
 'applicability=',
 'applicability=36',
 'applicability=43',
 'applicability=41',
 'applicability=55',
 'applicability=3',
 'applicability=22',
 'applicability=60',
 'applicability=58',
 'applicability=25',
 'applicability=47',
 'applicability=12',
 'applicability=38',
 'applicability=20',
 'applicability=18',
 'applicability=24',
 'applicability=62',
 'applicability=21',
 'applicability=23',
 'applicability=8',
 'applicability=26',
 'applicability=53',
 'applicability=15',
 'applicability=48',
 'applicability=14',
 'applicability=51',
 'applicability=13',
 'applicability=5',
 'applicability=7',
 'applicability=50',
 'applicability=52',
 'applicability=28',
 'applicability=29',
 'applicability=31',
 'applicability=6',
 'applicability=81',
 'applicability=66',
 'applicability=49',
 'applicability=33',
 'applicability=63',
 'applicability=68',
 'applicability=46',
 'applicability=19',
 'applicability=40',
 'applicability=17',
 'applicability=32',
 'applicability=72',
 'applicability=34',
 'applicability=35',
 'applicability=54',
 'applicability=27',
 'applicability=16',
 'applicability=64',
 'applicability=57',
 'applicability=56',
 'applicability=2',
 'applicability=4',
 'applicability=67',
 'applicability=77',
 'applicability=71',
 'applicability=59',
 'paragraphs=3',
 'paragraphs=6',
 'paragraphs=6-1',
 'paragraphs=6-3-c',
 'paragraphs=P1-3',
 'paragraphs=5',
 'paragraphs=5-1',
 'paragraphs=P1-1',
 'paragraphs=8',
 'paragraphs=8-1',
 'paragraphs=13',
 'paragraphs=10',
 'paragraphs=10-2',
 'paragraphs=10-1',
 'paragraphs=35-1',
 'paragraphs=2',
 'paragraphs=2-1',
 'paragraphs=34',
 'paragraphs=41',
 'paragraphs=38',
 'paragraphs=35',
 'paragraphs=8-2',
 'paragraphs=35-3-a',
 'paragraphs=29-3',
 'paragraphs=4',
 'paragraphs=29',
 'paragraphs=P1-1-1',
 'paragraphs=5-1-e',
 'paragraphs=6-2',
 'paragraphs=5-1-c',
 'paragraphs=14',
 'paragraphs=35-3',
 'paragraphs=6-3-d',
 'paragraphs=5-1-b',
 'paragraphs=5-5',
 'paragraphs=P12-1',
 'paragraphs=11-1',
 'paragraphs=11-2',
 'paragraphs=9',
 'paragraphs=9-1',
 'paragraphs=1',
 'paragraphs=11',
 'paragraphs=6-3',
 'paragraphs=5-3',
 'paragraphs=5-4',
 'paragraphs=46',
 'paragraphs=46-2',
 'paragraphs=5-1-a',
 'paragraphs=P4-2',
 'paragraphs=P4-2-2',
 'paragraphs=17',
 'paragraphs=18',
 'paragraphs=7',
 'paragraphs=7-1',
 'paragraphs=',
 'paragraphs=4-3-d',
 'paragraphs=4-2',
 'paragraphs=6-3-e',
 'paragraphs=9-2',
 'paragraphs=P1-1-2',
 'paragraphs=P4-2-1',
 'paragraphs=37-1-c',
 'paragraphs=37',
 'paragraphs=P7-4',
 'paragraphs=4-1',
 'paragraphs=57',
 'paragraphs=6-3-b',
 'paragraphs=35-3-b',
 'paragraphs=5-1-f',
 'paragraphs=35-4',
 'paragraphs=P4-2-3',
 'paragraphs=2-2',
 'paragraphs=26',
 'paragraphs=27-2',
 'paragraphs=27',
 'paragraphs=36',
 'paragraphs=36-1',
 'paragraphs=37-1',
 'paragraphs=P7-2',
 'paragraphs=35-2',
 'paragraphs=5-1-d',
 'paragraphs=6-3-a',
 'paragraphs=30',
 'paragraphs=46-1',
 'paragraphs=12',
 'paragraphs=P7-1',
 'paragraphs=P7-1-1',
 'paragraphs=36-2',
 'paragraphs=5-2',
 'paragraphs=P1-2',
 'paragraphs=P1-4',
 'paragraphs=56-3',
 'paragraphs=56',
 'paragraphs=56-1',
 'paragraphs=P7-1-2',
 'paragraphs=38-1-a',
 'paragraphs=37-1-b',
 'paragraphs=39',
 'paragraphs=15-1',
 'paragraphs=15',
 'paragraphs=7-2',
 'paragraphs=P4-4',
 'paragraphs=15-3',
 'paragraphs=25-1',
 'paragraphs=25',
 'paragraphs=37-1-a',
 'paragraphs=P6-1',
 'paragraphs=P7-5',
 'paragraphs=19',
 'paragraphs=32',
 'paragraphs=P7-3',
 'paragraphs=33',
 'paragraphs=28-1-a',
 'paragraphs=53',
 'paragraphs=28',
 'paragraphs=35-2-b',
 'paragraphs=43',
 'paragraphs=4-3-b',
 'paragraphs=4-3-a',
 'paragraphs=4-3',
 'paragraphs=28-3',
 'paragraphs=52',
 'paragraphs=P13-1',
 'paragraphs=P7-4-1',
 'paragraphs=16',
 'paragraphs=P4-3',
 'paragraphs=27-1-b',
 'paragraphs=29-1',
 'paragraphs=32-2',
 'paragraphs=28-1',
 'paragraphs=P6-2',
 'paragraphs=46-4',
 'ccl_article=1',
 'ccl_article=10',
 'ccl_article=11',
 'ccl_article=12',
 'ccl_article=13',
 'ccl_article=14',
 'ccl_article=17',
 'ccl_article=18',
 'ccl_article=2',
 'ccl_article=25',
 'ccl_article=3',
 'ccl_article=34',
 'ccl_article=38',
 'ccl_article=4',
 'ccl_article=46',
 'ccl_article=5',
 'ccl_article=6',
 'ccl_article=7',
 'ccl_article=8',
 'ccl_article=9',
 'ccl_article=p1',
 'ccl_article=p12',
 'ccl_article=p4',
 'ccl_article=p6',
 'ccl_article=p7',
 'importance']

In [85]:
df.isnull().any()

appno                   False
country.name            False
doctypebranch           False
originatingbody         False
originatingbody_name    False
                        ...
ccl_article=p12         False
ccl_article=p4          False
ccl_article=p6          False
ccl_article=p7          False
importance              False
Length: 291, dtype: bool

In [86]:
from sklearn import preprocessing

In [87]:
label_encoder = preprocessing.LabelEncoder()

In [88]:
df['country.name']= label_encoder.fit_transform(df['country.name'])

In [89]:
df['doctypebranch']= label_encoder.fit_transform(df['doctypebranch'])

In [90]:
df['originatingbody_type']= label_encoder.fit_transform(df['originatingbody_type'])

In [91]:
df['respondent.0']= label_encoder.fit_transform(df['respondent.0'])
df['respondentOrderEng']= label_encoder.fit_transform(df['respondentOrderEng'])
df=df.drop(['respondent.1','respondent.2','respondent.3','respondent.4'],axis=1)

In [92]:
df['originatingbody_name']= label_encoder.fit_transform(df['originatingbody_name'])

In [93]:
df=df.drop(['parties.2','parties.1','parties.0'],axis=1)

In [94]:
X = df[['appno']]
df=df.drop(['appno'],axis=1)

In [131]:
Y = df[['importance']]
df=df.drop(['importance'],axis=1)

In [132]:
# df['kpdate'] = pd.to_datetime(df['kpdate'])
# df = df.assign(
#                day_k=df.kpdate.dt.day,
#                month_k=df.kpdate.dt.month,
#                year_k=df.kpdate.dt.year)

# df = df.drop(['kpdate'],axis = 1)

In [133]:
from sklearn.model_selection import train_test_split

In [134]:
X_train,X_test,y_train,y_test=train_test_split(df,Y,random_state=0,test_size=.2)

In [135]:
l = [X for X in X_train.columns]
len(l)

282

# Random Forest

In [136]:
from sklearn.ensemble import RandomForestClassifier

In [137]:
rf = RandomForestClassifier(random_state=1,n_estimators=100)

In [138]:
rf.fit(X_train,y_train)

C:\Users\RISHAB\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [139]:
predict_rf=rf.predict(X_test)

In [140]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score

In [141]:
print(mean_absolute_error(predict_rf,y_test))
print(accuracy_score(predict_rf,y_test))

0.18074324324324326
0.8671171171171171

## Test

In [158]:
test = pd.read_csv("test.csv")

C:\Users\RISHAB\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (14,15,16,17,18,19,20,22,23,24,25,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [159]:

test = test.drop(['application','country.alpha2','docname','introductiondate'],axis=1)

In [160]:
test = test.drop(['decisiondate','ecli','issue.0','issue.1','issue.2','issue.3','issue.4','issue.5' \
             
             ,'issue.6','issue.7','issue.8','issue.9','issue.10','issue.11','issue.12','issue.13' \
             
             ,'issue.14','issue.15','issue.16','issue.17','issue.18','issue.19','issue.20','issue.21','issue.22'\
             
             ,'issue.23','issue.24','issue.25','issue.26'],axis=1)

In [161]:
test = test.drop(['itemid','languageisocode','kpdate','judgementdate'],axis=1)

In [162]:
test['country.name']= label_encoder.fit_transform(test['country.name'])

In [163]:
test['doctypebranch']= label_encoder.fit_transform(test['doctypebranch'])

In [164]:
test['originatingbody_type']= label_encoder.fit_transform(test['originatingbody_type'])

In [165]:
test['respondent.0']= label_encoder.fit_transform(test['respondent.0'])
test['respondentOrderEng']= label_encoder.fit_transform(test['respondentOrderEng'])
test=test.drop(['respondent.1','respondent.2','respondent.3','respondent.4'],axis=1)

In [166]:
test['originatingbody_name']= label_encoder.fit_transform(test['originatingbody_name'])

In [167]:
test=test.drop(['parties.2','parties.1','parties.0'],axis=1)

In [168]:
X_test = test['appno']
test=test.drop(['appno'],axis=1)

In [169]:
Y_test = rf.predict(test)

In [170]:
final = pd.DataFrame()

In [171]:
final['appno'] = X_test

In [172]:
final['importance'] = Y_test

In [173]:
final.to_csv('file.csv',index=False)