In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("train.csv")

C:\Users\RISHAB\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (16,17,18,19,20,22,23,24,25,26,27,28,45,49,50,51) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [17]:
df

,appno,application,country.alpha2,country.name,decisiondate,docname,doctypebranch,ecli,introductiondate,issue.0,...,ccl_article=6,ccl_article=7,ccl_article=8,ccl_article=9,ccl_article=p1,ccl_article=p12,ccl_article=p4,ccl_article=p6,ccl_article=p7,importance
0,2052/08,MS WORD,ru,Russian Federation,NaN,CASE OF KOKOSHKINA v. RUSSIA,CHAMBER,ECLI:CE:ECHR:2009:0528JUD000205208,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
1,4728/07,MS WORD,tr,Turkey,NaN,CASE OF ÖZCAN v. TURKEY,COMMITTEE,ECLI:CE:ECHR:2018:0710JUD000472807,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
2,44135/06,MS WORD,si,Slovenia,NaN,CASE OF DANIJEL PEČNIK v. SLOVENIA,CHAMBER,ECLI:CE:ECHR:2012:1018JUD004413506,NaN,NaN,...,1,0,0,0,0,0,0,0,0,4
3,2607/08,MS WORD,ch,Switzerland,NaN,CASE OF PALANCI v. SWITZERLAND,CHAMBER,ECLI:CE:ECHR:2014:0325JUD000260708,NaN,NaN,...,0,0,-1,0,0,0,0,0,0,4
4,27001/06,MS WORD,ru,Russian Federation,NaN,CASE OF AMANAT ILYASOVA AND OTHERS v. RUSSIA,CHAMBER,ECLI:CE:ECHR:2009:1001JUD002700106,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8873,60085/12,MS WORD,ua,Ukraine,NaN,CASE OF RASHITOV AND OTHERS v. UKRAINE,COMMITTEE,ECLI:CE:ECHR:2018:0329JUD006008512,NaN,NaN,...,1,0,0,0,0,0,0,0,0,4
8874,19857/09,MS WORD,ru,Russian Federation,NaN,CASE OF URMANOV v. RUSSIA,COMMITTEE,ECLI:CE:ECHR:2016:1011JUD001985709,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
8875,67253/01,MS WORD,ru,Russian Federation,NaN,CASE OF BABUSHKIN v. RUSSIA,CHAMBER,ECLI:CE:ECHR:2007:1018JUD006725301,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
8876,26737/95,MS WORD,es,Spain,NaN,CASE OF BRUALLA GÓMEZ DE LA TORRE v. SPAIN,CHAMBER,ECLI:CE:ECHR:1997:1219JUD002673795,NaN,"Leases of Urban Property Act, section 135, as ...",...,-1,0,0,0,0,0,0,0,0,3
8877,21695/05,MS WORD,pl,Poland,NaN,CASE OF TUR v. POLAND,CHAMBER,ECLI:CE:ECHR:2007:1023JUD002169505,NaN,NaN,...,1,0,0,0,0,0,0,0,0,4

In [19]:
df.columns

Index(['appno', 'application', 'country.alpha2', 'country.name',
       'decisiondate', 'docname', 'doctypebranch', 'ecli', 'introductiondate',
       'issue.0',
       ...
       'ccl_article=6', 'ccl_article=7', 'ccl_article=8', 'ccl_article=9',
       'ccl_article=p1', 'ccl_article=p12', 'ccl_article=p4', 'ccl_article=p6',
       'ccl_article=p7', 'importance'],
      dtype='object', length=328)

In [6]:
df.describe()

,originatingbody,rank,respondentOrderEng,sharepointid,typedescription,article=3,article=6,article=P1,article=5,article=8,...,ccl_article=6,ccl_article=7,ccl_article=8,ccl_article=9,ccl_article=p1,ccl_article=p12,ccl_article=p4,ccl_article=p6,ccl_article=p7,importance
count,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,...,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000,8878.000000
mean,12.255688,1357.402719,32.342532,400864.536269,14.941879,0.180221,0.550800,0.177292,0.172787,0.116242,...,0.390178,-0.001802,0.043253,0.002591,0.064654,0.000113,0.001577,0.000225,0.000788,3.461703
std,9.504175,1446.218266,14.062796,57670.790798,0.279205,0.384393,0.497441,0.381937,0.378084,0.320533,...,0.599878,0.077974,0.320771,0.078671,0.282190,0.010613,0.058112,0.015008,0.048632,0.870096
min,4.000000,171.353943,1.000000,316255.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,1.000000
25%,5.000000,582.323181,20.000000,347609.500000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
50%,7.000000,788.466248,38.000000,394983.500000,15.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
75%,23.000000,1547.329742,45.000000,454025.250000,15.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
max,29.000000,9968.310547,49.000000,501627.000000,19.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000

In [21]:
df = df.drop(['application','country.alpha2','docname','introductiondate'],axis=1)

In [22]:
df.head()

,appno,country.name,decisiondate,doctypebranch,ecli,issue.0,issue.1,issue.10,issue.11,issue.12,...,ccl_article=6,ccl_article=7,ccl_article=8,ccl_article=9,ccl_article=p1,ccl_article=p12,ccl_article=p4,ccl_article=p6,ccl_article=p7,importance
0,2052/08,Russian Federation,NaN,CHAMBER,ECLI:CE:ECHR:2009:0528JUD000205208,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
1,4728/07,Turkey,NaN,COMMITTEE,ECLI:CE:ECHR:2018:0710JUD000472807,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4
2,44135/06,Slovenia,NaN,CHAMBER,ECLI:CE:ECHR:2012:1018JUD004413506,NaN,NaN,NaN,NaN,NaN,...,1,0,0,0,0,0,0,0,0,4
3,2607/08,Switzerland,NaN,CHAMBER,ECLI:CE:ECHR:2014:0325JUD000260708,NaN,NaN,NaN,NaN,NaN,...,0,0,-1,0,0,0,0,0,0,4
4,27001/06,Russian Federation,NaN,CHAMBER,ECLI:CE:ECHR:2009:1001JUD002700106,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,4

In [24]:
df = df.drop(['decisiondate','ecli','issue.0','issue.1','issue.2','issue.3','issue.4','issue.5' \
             
             ,'issue.6','issue.7','issue.8','issue.9','issue.10','issue.11','issue.12','issue.13' \
             
             ,'issue.14','issue.15','issue.16','issue.17','issue.18','issue.19','issue.20','issue.21','issue.22'\
             
             ,'issue.23','issue.24','issue.25','issue.26'],axis=1)

In [25]:
df.head()

,appno,country.name,doctypebranch,itemid,judgementdate,kpdate,languageisocode,originatingbody,originatingbody_name,originatingbody_type,...,ccl_article=6,ccl_article=7,ccl_article=8,ccl_article=9,ccl_article=p1,ccl_article=p12,ccl_article=p4,ccl_article=p6,ccl_article=p7,importance
0,2052/08,Russian Federation,CHAMBER,001-92699,28/05/2009,28/05/2009,ENG,4,First Section,Court,...,0,0,0,0,0,0,0,0,0,4
1,4728/07,Turkey,COMMITTEE,001-184490,10/07/2018,10/07/2018,ENG,26,Second Section Committee,Court,...,0,0,0,0,0,0,0,0,0,4
2,44135/06,Slovenia,CHAMBER,001-113810,18/10/2012,18/10/2012,ENG,23,Fith Section,Court,...,1,0,0,0,0,0,0,0,0,4
3,2607/08,Switzerland,CHAMBER,001-141929,25/03/2014,25/03/2014,ENG,5,Second Section,Court,...,0,0,-1,0,0,0,0,0,0,4
4,27001/06,Russian Federation,CHAMBER,001-94585,01/10/2009,01/10/2009,ENG,4,First Section,Court,...,0,0,0,0,0,0,0,0,0,4

In [27]:
df = df.drop(['itemid','languageisocode','kpdate','judgementdate'],axis=1)

In [28]:
df.head()

,appno,country.name,doctypebranch,originatingbody,originatingbody_name,originatingbody_type,parties.0,parties.1,parties.2,rank,...,ccl_article=6,ccl_article=7,ccl_article=8,ccl_article=9,ccl_article=p1,ccl_article=p12,ccl_article=p4,ccl_article=p6,ccl_article=p7,importance
0,2052/08,Russian Federation,CHAMBER,4,First Section,Court,KOKOSHKINA,RUSSIA,NaN,685.417419,...,0,0,0,0,0,0,0,0,0,4
1,4728/07,Turkey,COMMITTEE,26,Second Section Committee,Court,ÖZCAN,TURKEY,NaN,2641.901855,...,0,0,0,0,0,0,0,0,0,4
2,44135/06,Slovenia,CHAMBER,23,Fith Section,Court,DANIJEL PEČNIK,SLOVENIA,NaN,942.213440,...,1,0,0,0,0,0,0,0,0,4
3,2607/08,Switzerland,CHAMBER,5,Second Section,Court,PALANCI,SWITZERLAND,NaN,1121.770142,...,0,0,-1,0,0,0,0,0,0,4
4,27001/06,Russian Federation,CHAMBER,4,First Section,Court,AMANAT ILYASOVA AND OTHERS,RUSSIA,NaN,704.821594,...,0,0,0,0,0,0,0,0,0,4

In [35]:
df.column

AttributeError: 'DataFrame' object has no attribute 'column'

In [33]:
df.isnull().any()

appno                   False
country.name            False
doctypebranch           False
originatingbody         False
originatingbody_name    False
                        ...
ccl_article=p12         False
ccl_article=p4          False
ccl_article=p6          False
ccl_article=p7          False
importance              False
Length: 291, dtype: bool

In [29]:
from sklearn import preprocessing

In [30]:
label_encoder = preprocessing.LabelEncoder()

In [31]:
df['country.name']= label_encoder.fit_transform(df['country.name'])

In [32]:
df['doctypebranch']= label_encoder.fit_transform(df['doctypebranch'])

In [34]:
df['originatingbody_type']= label_encoder.fit_transform(df['originatingbody_type'])